/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class AddressBookInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AddressBookInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AddressBookInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_AddressBookInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AddressBookInfo() {
    this(klcppwrapJNI.new_AddressBookInfo(), true);
  }

  public void setId(String id_) {
    klcppwrapJNI.AddressBookInfo_setId(swigCPtr, this, id_);
  }

  public String id() {
    return klcppwrapJNI.AddressBookInfo_id(swigCPtr, this);
  }

  public void setName(String name_) {
    klcppwrapJNI.AddressBookInfo_setName(swigCPtr, this, name_);
  }

  public String name() {
    return klcppwrapJNI.AddressBookInfo_name(swigCPtr, this);
  }

  public void setAvailable(boolean isAvailable_) {
    klcppwrapJNI.AddressBookInfo_setAvailable(swigCPtr, this, isAvailable_);
  }

  public boolean isAvailable() {
    return klcppwrapJNI.AddressBookInfo_isAvailable(swigCPtr, this);
  }

}
