/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class AvatarMetadata {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AvatarMetadata(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AvatarMetadata obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_AvatarMetadata(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AvatarMetadata(String id_, int bytes_, String type_) {
    this(klcppwrapJNI.new_AvatarMetadata(id_, bytes_, type_), true);
  }

  public String id() {
    return klcppwrapJNI.AvatarMetadata_id(swigCPtr, this);
  }

  public String url() {
    return klcppwrapJNI.AvatarMetadata_url(swigCPtr, this);
  }

  public int bytes() {
    return klcppwrapJNI.AvatarMetadata_bytes(swigCPtr, this);
  }

  public int height() {
    return klcppwrapJNI.AvatarMetadata_height(swigCPtr, this);
  }

  public int width() {
    return klcppwrapJNI.AvatarMetadata_width(swigCPtr, this);
  }

  public String type() {
    return klcppwrapJNI.AvatarMetadata_type(swigCPtr, this);
  }

  public void setUrl(String url_) {
    klcppwrapJNI.AvatarMetadata_setUrl(swigCPtr, this, url_);
  }

  public void setHeight(int height_) {
    klcppwrapJNI.AvatarMetadata_setHeight(swigCPtr, this, height_);
  }

  public void setWidth(int width_) {
    klcppwrapJNI.AvatarMetadata_setWidth(swigCPtr, this, width_);
  }

}
