/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class BackgroundInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BackgroundInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BackgroundInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_BackgroundInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BackgroundInfo() {
    this(klcppwrapJNI.new_BackgroundInfo(), true);
  }

  public void setId(String id_) {
    klcppwrapJNI.BackgroundInfo_setId(swigCPtr, this, id_);
  }

  public String id() {
    return klcppwrapJNI.BackgroundInfo_id(swigCPtr, this);
  }

  public void setType(String type_) {
    klcppwrapJNI.BackgroundInfo_setType(swigCPtr, this, type_);
  }

  public String type() {
    return klcppwrapJNI.BackgroundInfo_type(swigCPtr, this);
  }

  public void setUrl(String url_) {
    klcppwrapJNI.BackgroundInfo_setUrl(swigCPtr, this, url_);
  }

  public String url() {
    return klcppwrapJNI.BackgroundInfo_url(swigCPtr, this);
  }

  public void setBytes(int bytes_) {
    klcppwrapJNI.BackgroundInfo_setBytes(swigCPtr, this, bytes_);
  }

  public int bytes() {
    return klcppwrapJNI.BackgroundInfo_bytes(swigCPtr, this);
  }

  public void setHeight(int height_) {
    klcppwrapJNI.BackgroundInfo_setHeight(swigCPtr, this, height_);
  }

  public int height() {
    return klcppwrapJNI.BackgroundInfo_height(swigCPtr, this);
  }

  public void setWidth(int width_) {
    klcppwrapJNI.BackgroundInfo_setWidth(swigCPtr, this, width_);
  }

  public int width() {
    return klcppwrapJNI.BackgroundInfo_width(swigCPtr, this);
  }

}
