/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class Bytestream {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Bytestream(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Bytestream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_Bytestream(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean isOpen() {
    return klcppwrapJNI.Bytestream_isOpen(swigCPtr, this);
  }

  public String sid() {
    return klcppwrapJNI.Bytestream_sid(swigCPtr, this);
  }

  public Bytestream.StreamType type() {
    return Bytestream.StreamType.swigToEnum(klcppwrapJNI.Bytestream_type(swigCPtr, this));
  }

  public JID target() {
    return new JID(klcppwrapJNI.Bytestream_target(swigCPtr, this), false);
  }

  public JID initiator() {
    return new JID(klcppwrapJNI.Bytestream_initiator(swigCPtr, this), false);
  }

  public final static class StreamType {
    public final static Bytestream.StreamType S5B = new Bytestream.StreamType("S5B");
    public final static Bytestream.StreamType IBB = new Bytestream.StreamType("IBB");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static StreamType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + StreamType.class + " with value " + swigValue);
    }

    private StreamType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private StreamType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private StreamType(String swigName, StreamType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static StreamType[] swigValues = { S5B, IBB };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
