/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class BytestreamData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BytestreamData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BytestreamData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_BytestreamData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BytestreamData(String data_) {
    this(klcppwrapJNI.new_BytestreamData(data_), true);
  }

  public long copy(byte[] output_, long maxsize_) {
    return klcppwrapJNI.BytestreamData_copy(swigCPtr, this, output_, maxsize_);
  }

  public long length() {
    return klcppwrapJNI.BytestreamData_length(swigCPtr, this);
  }

}
