/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class CertInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CertInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CertInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_CertInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStatus(int value) {
    klcppwrapJNI.CertInfo_status_set(swigCPtr, this, value);
  }

  public int getStatus() {
    return klcppwrapJNI.CertInfo_status_get(swigCPtr, this);
  }

  public void setChain(boolean value) {
    klcppwrapJNI.CertInfo_chain_set(swigCPtr, this, value);
  }

  public boolean getChain() {
    return klcppwrapJNI.CertInfo_chain_get(swigCPtr, this);
  }

  public void setIssuer(String value) {
    klcppwrapJNI.CertInfo_issuer_set(swigCPtr, this, value);
  }

  public String getIssuer() {
    return klcppwrapJNI.CertInfo_issuer_get(swigCPtr, this);
  }

  public void setServer(String value) {
    klcppwrapJNI.CertInfo_server_set(swigCPtr, this, value);
  }

  public String getServer() {
    return klcppwrapJNI.CertInfo_server_get(swigCPtr, this);
  }

  public void setDate_from(int value) {
    klcppwrapJNI.CertInfo_date_from_set(swigCPtr, this, value);
  }

  public int getDate_from() {
    return klcppwrapJNI.CertInfo_date_from_get(swigCPtr, this);
  }

  public void setDate_to(int value) {
    klcppwrapJNI.CertInfo_date_to_set(swigCPtr, this, value);
  }

  public int getDate_to() {
    return klcppwrapJNI.CertInfo_date_to_get(swigCPtr, this);
  }

  public void setProtocol(String value) {
    klcppwrapJNI.CertInfo_protocol_set(swigCPtr, this, value);
  }

  public String getProtocol() {
    return klcppwrapJNI.CertInfo_protocol_get(swigCPtr, this);
  }

  public void setCipher(String value) {
    klcppwrapJNI.CertInfo_cipher_set(swigCPtr, this, value);
  }

  public String getCipher() {
    return klcppwrapJNI.CertInfo_cipher_get(swigCPtr, this);
  }

  public void setMac(String value) {
    klcppwrapJNI.CertInfo_mac_set(swigCPtr, this, value);
  }

  public String getMac() {
    return klcppwrapJNI.CertInfo_mac_get(swigCPtr, this);
  }

  public void setCompression(String value) {
    klcppwrapJNI.CertInfo_compression_set(swigCPtr, this, value);
  }

  public String getCompression() {
    return klcppwrapJNI.CertInfo_compression_get(swigCPtr, this);
  }

  public CertInfo() {
    this(klcppwrapJNI.new_CertInfo(), true);
  }

}
