/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public final class CertStatus {
  public final static CertStatus CertOk = new CertStatus("CertOk", klcppwrapJNI.CertOk_get());
  public final static CertStatus CertInvalid = new CertStatus("CertInvalid", klcppwrapJNI.CertInvalid_get());
  public final static CertStatus CertSignerUnknown = new CertStatus("CertSignerUnknown", klcppwrapJNI.CertSignerUnknown_get());
  public final static CertStatus CertRevoked = new CertStatus("CertRevoked", klcppwrapJNI.CertRevoked_get());
  public final static CertStatus CertExpired = new CertStatus("CertExpired", klcppwrapJNI.CertExpired_get());
  public final static CertStatus CertNotActive = new CertStatus("CertNotActive", klcppwrapJNI.CertNotActive_get());
  public final static CertStatus CertWrongPeer = new CertStatus("CertWrongPeer", klcppwrapJNI.CertWrongPeer_get());
  public final static CertStatus CertSignerNotCa = new CertStatus("CertSignerNotCa", klcppwrapJNI.CertSignerNotCa_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CertStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CertStatus.class + " with value " + swigValue);
  }

  private CertStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CertStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CertStatus(String swigName, CertStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CertStatus[] swigValues = { CertOk, CertInvalid, CertSignerUnknown, CertRevoked, CertExpired, CertNotActive, CertWrongPeer, CertSignerNotCa };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

