/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public final class ChatStateType {
  public final static ChatStateType ChatStateActive = new ChatStateType("ChatStateActive", klcppwrapJNI.ChatStateActive_get());
  public final static ChatStateType ChatStateComposing = new ChatStateType("ChatStateComposing", klcppwrapJNI.ChatStateComposing_get());
  public final static ChatStateType ChatStatePaused = new ChatStateType("ChatStatePaused", klcppwrapJNI.ChatStatePaused_get());
  public final static ChatStateType ChatStateInactive = new ChatStateType("ChatStateInactive", klcppwrapJNI.ChatStateInactive_get());
  public final static ChatStateType ChatStateGone = new ChatStateType("ChatStateGone", klcppwrapJNI.ChatStateGone_get());
  public final static ChatStateType ChatStateInvalid = new ChatStateType("ChatStateInvalid", klcppwrapJNI.ChatStateInvalid_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ChatStateType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ChatStateType.class + " with value " + swigValue);
  }

  private ChatStateType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ChatStateType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ChatStateType(String swigName, ChatStateType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ChatStateType[] swigValues = { ChatStateActive, ChatStateComposing, ChatStatePaused, ChatStateInactive, ChatStateGone, ChatStateInvalid };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

