/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public final class CreateMUCRoomError {
  public final static CreateMUCRoomError Unknown = new CreateMUCRoomError("Unknown");
  public final static CreateMUCRoomError NotAllowed = new CreateMUCRoomError("NotAllowed");
  public final static CreateMUCRoomError RemoteServerNotFound = new CreateMUCRoomError("RemoteServerNotFound");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CreateMUCRoomError swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CreateMUCRoomError.class + " with value " + swigValue);
  }

  private CreateMUCRoomError(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CreateMUCRoomError(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CreateMUCRoomError(String swigName, CreateMUCRoomError swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CreateMUCRoomError[] swigValues = { Unknown, NotAllowed, RemoteServerNotFound };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

