/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class DiscoIdentityList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DiscoIdentityList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DiscoIdentityList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_DiscoIdentityList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DiscoIdentityList() {
    this(klcppwrapJNI.new_DiscoIdentityList(), true);
  }

  public long size() {
    return klcppwrapJNI.DiscoIdentityList_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return klcppwrapJNI.DiscoIdentityList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    klcppwrapJNI.DiscoIdentityList_clear(swigCPtr, this);
  }

  public void add(SWIGTYPE_p_gloox__Disco__Identity x) {
    klcppwrapJNI.DiscoIdentityList_add(swigCPtr, this, SWIGTYPE_p_gloox__Disco__Identity.getCPtr(x));
  }

  public SWIGTYPE_p_gloox__Disco__Identity get(int index) {
    long cPtr = klcppwrapJNI.DiscoIdentityList_get(swigCPtr, this, index);
    return (cPtr == 0) ? null : new SWIGTYPE_p_gloox__Disco__Identity(cPtr, false);
  }

}
