/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class EntityInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EntityInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EntityInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_EntityInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EntityInfo() {
    this(klcppwrapJNI.new_EntityInfo(), true);
  }

  public void setIdentities(DiscoIdentityList identities_) {
    klcppwrapJNI.EntityInfo_setIdentities(swigCPtr, this, DiscoIdentityList.getCPtr(identities_), identities_);
  }

  public DiscoIdentityList identities() {
    return new DiscoIdentityList(klcppwrapJNI.EntityInfo_identities(swigCPtr, this), false);
  }

  public void setFeatures(StringList features_) {
    klcppwrapJNI.EntityInfo_setFeatures(swigCPtr, this, StringList.getCPtr(features_), features_);
  }

  public StringList features() {
    return new StringList(klcppwrapJNI.EntityInfo_features(swigCPtr, this), false);
  }

}
