/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class Geoloc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Geoloc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Geoloc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_Geoloc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Geoloc() {
    this(klcppwrapJNI.new_Geoloc(), true);
  }

  public void setAccuracy(double accuracy_) {
    klcppwrapJNI.Geoloc_setAccuracy(swigCPtr, this, accuracy_);
  }

  public double accuracy() {
    return klcppwrapJNI.Geoloc_accuracy(swigCPtr, this);
  }

  public void setAlt(double alt_) {
    klcppwrapJNI.Geoloc_setAlt(swigCPtr, this, alt_);
  }

  public double alt() {
    return klcppwrapJNI.Geoloc_alt(swigCPtr, this);
  }

  public void setArea(String area_) {
    klcppwrapJNI.Geoloc_setArea(swigCPtr, this, area_);
  }

  public String area() {
    return klcppwrapJNI.Geoloc_area(swigCPtr, this);
  }

  public void setBearing(double bearing_) {
    klcppwrapJNI.Geoloc_setBearing(swigCPtr, this, bearing_);
  }

  public double bearing() {
    return klcppwrapJNI.Geoloc_bearing(swigCPtr, this);
  }

  public void setBuilding(String building_) {
    klcppwrapJNI.Geoloc_setBuilding(swigCPtr, this, building_);
  }

  public String building() {
    return klcppwrapJNI.Geoloc_building(swigCPtr, this);
  }

  public void setCountry(String country_) {
    klcppwrapJNI.Geoloc_setCountry(swigCPtr, this, country_);
  }

  public String country() {
    return klcppwrapJNI.Geoloc_country(swigCPtr, this);
  }

  public void setCountrycode(String countrycode_) {
    klcppwrapJNI.Geoloc_setCountrycode(swigCPtr, this, countrycode_);
  }

  public String countrycode() {
    return klcppwrapJNI.Geoloc_countrycode(swigCPtr, this);
  }

  public void setDatum(String datum_) {
    klcppwrapJNI.Geoloc_setDatum(swigCPtr, this, datum_);
  }

  public String datum() {
    return klcppwrapJNI.Geoloc_datum(swigCPtr, this);
  }

  public void setDescription(String description_) {
    klcppwrapJNI.Geoloc_setDescription(swigCPtr, this, description_);
  }

  public String description() {
    return klcppwrapJNI.Geoloc_description(swigCPtr, this);
  }

  public void setError(double error_) {
    klcppwrapJNI.Geoloc_setError(swigCPtr, this, error_);
  }

  public double error() {
    return klcppwrapJNI.Geoloc_error(swigCPtr, this);
  }

  public void setFloor(String floor_) {
    klcppwrapJNI.Geoloc_setFloor(swigCPtr, this, floor_);
  }

  public String floor() {
    return klcppwrapJNI.Geoloc_floor(swigCPtr, this);
  }

  public void setLat(double lat_) {
    klcppwrapJNI.Geoloc_setLat(swigCPtr, this, lat_);
  }

  public double lat() {
    return klcppwrapJNI.Geoloc_lat(swigCPtr, this);
  }

  public void setLocality(String locality_) {
    klcppwrapJNI.Geoloc_setLocality(swigCPtr, this, locality_);
  }

  public String locality() {
    return klcppwrapJNI.Geoloc_locality(swigCPtr, this);
  }

  public void setLon(double lon_) {
    klcppwrapJNI.Geoloc_setLon(swigCPtr, this, lon_);
  }

  public double lon() {
    return klcppwrapJNI.Geoloc_lon(swigCPtr, this);
  }

  public void setPostalcode(String postalcode_) {
    klcppwrapJNI.Geoloc_setPostalcode(swigCPtr, this, postalcode_);
  }

  public String postalcode() {
    return klcppwrapJNI.Geoloc_postalcode(swigCPtr, this);
  }

  public void setRegion(String region_) {
    klcppwrapJNI.Geoloc_setRegion(swigCPtr, this, region_);
  }

  public String region() {
    return klcppwrapJNI.Geoloc_region(swigCPtr, this);
  }

  public void setRoom(String room_) {
    klcppwrapJNI.Geoloc_setRoom(swigCPtr, this, room_);
  }

  public String room() {
    return klcppwrapJNI.Geoloc_room(swigCPtr, this);
  }

  public void setSpeed(double speed_) {
    klcppwrapJNI.Geoloc_setSpeed(swigCPtr, this, speed_);
  }

  public double speed() {
    return klcppwrapJNI.Geoloc_speed(swigCPtr, this);
  }

  public void setStreet(String street_) {
    klcppwrapJNI.Geoloc_setStreet(swigCPtr, this, street_);
  }

  public String street() {
    return klcppwrapJNI.Geoloc_street(swigCPtr, this);
  }

  public void setText(String text_) {
    klcppwrapJNI.Geoloc_setText(swigCPtr, this, text_);
  }

  public String text() {
    return klcppwrapJNI.Geoloc_text(swigCPtr, this);
  }

  public void setTimestamp(String timestamp_) {
    klcppwrapJNI.Geoloc_setTimestamp(swigCPtr, this, timestamp_);
  }

  public String timestamp() {
    return klcppwrapJNI.Geoloc_timestamp(swigCPtr, this);
  }

  public void setTzo(String tzo_) {
    klcppwrapJNI.Geoloc_setTzo(swigCPtr, this, tzo_);
  }

  public String tzo() {
    return klcppwrapJNI.Geoloc_tzo(swigCPtr, this);
  }

  public void setUri(String uri_) {
    klcppwrapJNI.Geoloc_setUri(swigCPtr, this, uri_);
  }

  public String uri() {
    return klcppwrapJNI.Geoloc_uri(swigCPtr, this);
  }

}
