/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class IMailSMTPInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IMailSMTPInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IMailSMTPInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_IMailSMTPInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IMailSMTPInfo() {
    this(klcppwrapJNI.new_IMailSMTPInfo(), true);
  }

  public void setMessageID(String messageID_) {
    klcppwrapJNI.IMailSMTPInfo_setMessageID(swigCPtr, this, messageID_);
  }

  public String messageID() {
    return klcppwrapJNI.IMailSMTPInfo_messageID(swigCPtr, this);
  }

  public void setTitle(String title_) {
    klcppwrapJNI.IMailSMTPInfo_setTitle(swigCPtr, this, title_);
  }

  public String title() {
    return klcppwrapJNI.IMailSMTPInfo_title(swigCPtr, this);
  }

  public void setAttachmentNum(int attachmentNum_) {
    klcppwrapJNI.IMailSMTPInfo_setAttachmentNum(swigCPtr, this, attachmentNum_);
  }

  public int attachmentNum() {
    return klcppwrapJNI.IMailSMTPInfo_attachmentNum(swigCPtr, this);
  }

}
