/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class JID {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected JID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_JID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public JID() {
    this(klcppwrapJNI.new_JID__SWIG_0(), true);
  }

  public JID(String jid) {
    this(klcppwrapJNI.new_JID__SWIG_1(jid), true);
  }

  public boolean setJID(String jid) {
    return klcppwrapJNI.JID_setJID(swigCPtr, this, jid);
  }

  public String full() {
    return klcppwrapJNI.JID_full(swigCPtr, this);
  }

  public String bare() {
    return klcppwrapJNI.JID_bare(swigCPtr, this);
  }

  public JID bareJID() {
    return new JID(klcppwrapJNI.JID_bareJID(swigCPtr, this), true);
  }

  public boolean setUsername(String username) {
    return klcppwrapJNI.JID_setUsername(swigCPtr, this, username);
  }

  public boolean setServer(String server) {
    return klcppwrapJNI.JID_setServer(swigCPtr, this, server);
  }

  public boolean setResource(String resource) {
    return klcppwrapJNI.JID_setResource(swigCPtr, this, resource);
  }

  public String username() {
    return klcppwrapJNI.JID_username(swigCPtr, this);
  }

  public String server() {
    return klcppwrapJNI.JID_server(swigCPtr, this);
  }

  public String serverRaw() {
    return klcppwrapJNI.JID_serverRaw(swigCPtr, this);
  }

  public String resource() {
    return klcppwrapJNI.JID_resource(swigCPtr, this);
  }

  public static String escapeNode(String node) {
    return klcppwrapJNI.JID_escapeNode(node);
  }

  public static String unescapeNode(String node) {
    return klcppwrapJNI.JID_unescapeNode(node);
  }

}
