/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class klcppwrap {
  public static String getKLXMPP_VERSION() {
    return klcppwrapJNI.KLXMPP_VERSION_get();
  }

  public static String getXMLNS_X_CONFERENCE() {
    return klcppwrapJNI.XMLNS_X_CONFERENCE_get();
  }

  public static String getXMLNS_AVATAR_DATA() {
    return klcppwrapJNI.XMLNS_AVATAR_DATA_get();
  }

  public static String getXMLNS_AVATAR_METADATA() {
    return klcppwrapJNI.XMLNS_AVATAR_METADATA_get();
  }

  public static String getXMLNS_MICROBLOG() {
    return klcppwrapJNI.XMLNS_MICROBLOG_get();
  }

  public static String getXMLNS_ATOM() {
    return klcppwrapJNI.XMLNS_ATOM_get();
  }

  public static String getXMLNS_GEOLOC() {
    return klcppwrapJNI.XMLNS_GEOLOC_get();
  }

  public static String getXMLNS_NEEKLE_PERSONALINFO() {
    return klcppwrapJNI.XMLNS_NEEKLE_PERSONALINFO_get();
  }

  public static String getXMLNS_NEEKLE_ADDRESSBOOK() {
    return klcppwrapJNI.XMLNS_NEEKLE_ADDRESSBOOK_get();
  }

  public static String getXMLNS_NEEKLE_BACKGROUND() {
    return klcppwrapJNI.XMLNS_NEEKLE_BACKGROUND_get();
  }

  public static String getXMLNS_NEEKLE_IMAIL() {
    return klcppwrapJNI.XMLNS_NEEKLE_IMAIL_get();
  }

  public static String getTAG_NAME_ID() {
    return klcppwrapJNI.TAG_NAME_ID_get();
  }

  public static String getTAG_NAME_NAME() {
    return klcppwrapJNI.TAG_NAME_NAME_get();
  }

  public static String getTAG_NAME_AVAILABLE() {
    return klcppwrapJNI.TAG_NAME_AVAILABLE_get();
  }

  public static String getTAG_NAME_BACKGROUND() {
    return klcppwrapJNI.TAG_NAME_BACKGROUND_get();
  }

  public static String getTAG_NAME_INFO() {
    return klcppwrapJNI.TAG_NAME_INFO_get();
  }

  public static String getTAG_NAME_ADDRESSBOOK() {
    return klcppwrapJNI.TAG_NAME_ADDRESSBOOK_get();
  }

  public static String getATTRIBUTE_NAME_ID() {
    return klcppwrapJNI.ATTRIBUTE_NAME_ID_get();
  }

  public static String getATTRIBUTE_NAME_TYPE() {
    return klcppwrapJNI.ATTRIBUTE_NAME_TYPE_get();
  }

  public static String getATTRIBUTE_NAME_URL() {
    return klcppwrapJNI.ATTRIBUTE_NAME_URL_get();
  }

  public static String getATTRIBUTE_NAME_BYTES() {
    return klcppwrapJNI.ATTRIBUTE_NAME_BYTES_get();
  }

  public static String getATTRIBUTE_NAME_HEIGHT() {
    return klcppwrapJNI.ATTRIBUTE_NAME_HEIGHT_get();
  }

  public static String getATTRIBUTE_NAME_WIDTH() {
    return klcppwrapJNI.ATTRIBUTE_NAME_WIDTH_get();
  }

  public static String klxmpp_version() {
    return klcppwrapJNI.klxmpp_version();
  }

}
