/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public final class LogArea {
  public final static LogArea LogAreaClassParser = new LogArea("LogAreaClassParser", klcppwrapJNI.LogAreaClassParser_get());
  public final static LogArea LogAreaClassConnectionTCPBase = new LogArea("LogAreaClassConnectionTCPBase", klcppwrapJNI.LogAreaClassConnectionTCPBase_get());
  public final static LogArea LogAreaClassClient = new LogArea("LogAreaClassClient", klcppwrapJNI.LogAreaClassClient_get());
  public final static LogArea LogAreaClassClientbase = new LogArea("LogAreaClassClientbase", klcppwrapJNI.LogAreaClassClientbase_get());
  public final static LogArea LogAreaClassComponent = new LogArea("LogAreaClassComponent", klcppwrapJNI.LogAreaClassComponent_get());
  public final static LogArea LogAreaClassDns = new LogArea("LogAreaClassDns", klcppwrapJNI.LogAreaClassDns_get());
  public final static LogArea LogAreaClassConnectionHTTPProxy = new LogArea("LogAreaClassConnectionHTTPProxy", klcppwrapJNI.LogAreaClassConnectionHTTPProxy_get());
  public final static LogArea LogAreaClassConnectionSOCKS5Proxy = new LogArea("LogAreaClassConnectionSOCKS5Proxy", klcppwrapJNI.LogAreaClassConnectionSOCKS5Proxy_get());
  public final static LogArea LogAreaClassConnectionTCPClient = new LogArea("LogAreaClassConnectionTCPClient", klcppwrapJNI.LogAreaClassConnectionTCPClient_get());
  public final static LogArea LogAreaClassConnectionTCPServer = new LogArea("LogAreaClassConnectionTCPServer", klcppwrapJNI.LogAreaClassConnectionTCPServer_get());
  public final static LogArea LogAreaClassS5BManager = new LogArea("LogAreaClassS5BManager", klcppwrapJNI.LogAreaClassS5BManager_get());
  public final static LogArea LogAreaClassSOCKS5Bytestream = new LogArea("LogAreaClassSOCKS5Bytestream", klcppwrapJNI.LogAreaClassSOCKS5Bytestream_get());
  public final static LogArea LogAreaClassConnectionBOSH = new LogArea("LogAreaClassConnectionBOSH", klcppwrapJNI.LogAreaClassConnectionBOSH_get());
  public final static LogArea LogAreaClassConnectionTLS = new LogArea("LogAreaClassConnectionTLS", klcppwrapJNI.LogAreaClassConnectionTLS_get());
  public final static LogArea LogAreaLinkLocalManager = new LogArea("LogAreaLinkLocalManager", klcppwrapJNI.LogAreaLinkLocalManager_get());
  public final static LogArea LogAreaAllClasses = new LogArea("LogAreaAllClasses", klcppwrapJNI.LogAreaAllClasses_get());
  public final static LogArea LogAreaXmlIncoming = new LogArea("LogAreaXmlIncoming", klcppwrapJNI.LogAreaXmlIncoming_get());
  public final static LogArea LogAreaXmlOutgoing = new LogArea("LogAreaXmlOutgoing", klcppwrapJNI.LogAreaXmlOutgoing_get());
  public final static LogArea LogAreaUser = new LogArea("LogAreaUser", klcppwrapJNI.LogAreaUser_get());
  public final static LogArea LogAreaAll = new LogArea("LogAreaAll", klcppwrapJNI.LogAreaAll_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LogArea swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LogArea.class + " with value " + swigValue);
  }

  private LogArea(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LogArea(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LogArea(String swigName, LogArea swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LogArea[] swigValues = { LogAreaClassParser, LogAreaClassConnectionTCPBase, LogAreaClassClient, LogAreaClassClientbase, LogAreaClassComponent, LogAreaClassDns, LogAreaClassConnectionHTTPProxy, LogAreaClassConnectionSOCKS5Proxy, LogAreaClassConnectionTCPClient, LogAreaClassConnectionTCPServer, LogAreaClassS5BManager, LogAreaClassSOCKS5Bytestream, LogAreaClassConnectionBOSH, LogAreaClassConnectionTLS, LogAreaLinkLocalManager, LogAreaAllClasses, LogAreaXmlIncoming, LogAreaXmlOutgoing, LogAreaUser, LogAreaAll };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

