/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public final class MessageEventType {
  public final static MessageEventType MessageEventOffline = new MessageEventType("MessageEventOffline", klcppwrapJNI.MessageEventOffline_get());
  public final static MessageEventType MessageEventDelivered = new MessageEventType("MessageEventDelivered", klcppwrapJNI.MessageEventDelivered_get());
  public final static MessageEventType MessageEventDisplayed = new MessageEventType("MessageEventDisplayed", klcppwrapJNI.MessageEventDisplayed_get());
  public final static MessageEventType MessageEventComposing = new MessageEventType("MessageEventComposing", klcppwrapJNI.MessageEventComposing_get());
  public final static MessageEventType MessageEventInvalid = new MessageEventType("MessageEventInvalid", klcppwrapJNI.MessageEventInvalid_get());
  public final static MessageEventType MessageEventCancel = new MessageEventType("MessageEventCancel", klcppwrapJNI.MessageEventCancel_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MessageEventType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MessageEventType.class + " with value " + swigValue);
  }

  private MessageEventType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MessageEventType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MessageEventType(String swigName, MessageEventType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MessageEventType[] swigValues = { MessageEventOffline, MessageEventDelivered, MessageEventDisplayed, MessageEventComposing, MessageEventInvalid, MessageEventCancel };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

