/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public final class MessageSessionFilter {
  public final static MessageSessionFilter FilterMessageEvents = new MessageSessionFilter("FilterMessageEvents", klcppwrapJNI.FilterMessageEvents_get());
  public final static MessageSessionFilter FilterChatStates = new MessageSessionFilter("FilterChatStates", klcppwrapJNI.FilterChatStates_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MessageSessionFilter swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MessageSessionFilter.class + " with value " + swigValue);
  }

  private MessageSessionFilter(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MessageSessionFilter(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MessageSessionFilter(String swigName, MessageSessionFilter swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MessageSessionFilter[] swigValues = { FilterMessageEvents, FilterChatStates };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

