/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public final class MUCRoomAffiliation {
  public final static MUCRoomAffiliation AffiliationNone = new MUCRoomAffiliation("AffiliationNone");
  public final static MUCRoomAffiliation AffiliationOutcast = new MUCRoomAffiliation("AffiliationOutcast");
  public final static MUCRoomAffiliation AffiliationMember = new MUCRoomAffiliation("AffiliationMember");
  public final static MUCRoomAffiliation AffiliationOwner = new MUCRoomAffiliation("AffiliationOwner");
  public final static MUCRoomAffiliation AffiliationAdmin = new MUCRoomAffiliation("AffiliationAdmin");
  public final static MUCRoomAffiliation AffiliationInvalid = new MUCRoomAffiliation("AffiliationInvalid");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MUCRoomAffiliation swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MUCRoomAffiliation.class + " with value " + swigValue);
  }

  private MUCRoomAffiliation(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MUCRoomAffiliation(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MUCRoomAffiliation(String swigName, MUCRoomAffiliation swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MUCRoomAffiliation[] swigValues = { AffiliationNone, AffiliationOutcast, AffiliationMember, AffiliationOwner, AffiliationAdmin, AffiliationInvalid };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

