/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public final class MUCRoomInvitationType {
  public final static MUCRoomInvitationType Mediated = new MUCRoomInvitationType("Mediated");
  public final static MUCRoomInvitationType Direct = new MUCRoomInvitationType("Direct");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MUCRoomInvitationType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MUCRoomInvitationType.class + " with value " + swigValue);
  }

  private MUCRoomInvitationType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MUCRoomInvitationType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MUCRoomInvitationType(String swigName, MUCRoomInvitationType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MUCRoomInvitationType[] swigValues = { Mediated, Direct };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

