/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public final class MUCRoomRole {
  public final static MUCRoomRole RoleNone = new MUCRoomRole("RoleNone");
  public final static MUCRoomRole RoleVisitor = new MUCRoomRole("RoleVisitor");
  public final static MUCRoomRole RoleParticipant = new MUCRoomRole("RoleParticipant");
  public final static MUCRoomRole RoleModerator = new MUCRoomRole("RoleModerator");
  public final static MUCRoomRole RoleInvalid = new MUCRoomRole("RoleInvalid");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MUCRoomRole swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MUCRoomRole.class + " with value " + swigValue);
  }

  private MUCRoomRole(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MUCRoomRole(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MUCRoomRole(String swigName, MUCRoomRole swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MUCRoomRole[] swigValues = { RoleNone, RoleVisitor, RoleParticipant, RoleModerator, RoleInvalid };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

