/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class MUCRoomConfig {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MUCRoomConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MUCRoomConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_MUCRoomConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MUCRoomConfig() {
    this(klcppwrapJNI.new_MUCRoomConfig(), true);
  }

  public void setRoomname(String value) {
    klcppwrapJNI.MUCRoomConfig_roomname_set(swigCPtr, this, value);
  }

  public String getRoomname() {
    return klcppwrapJNI.MUCRoomConfig_roomname_get(swigCPtr, this);
  }

  public void setRoomdesc(String value) {
    klcppwrapJNI.MUCRoomConfig_roomdesc_set(swigCPtr, this, value);
  }

  public String getRoomdesc() {
    return klcppwrapJNI.MUCRoomConfig_roomdesc_get(swigCPtr, this);
  }

  public void setEnableLogging(boolean value) {
    klcppwrapJNI.MUCRoomConfig_enableLogging_set(swigCPtr, this, value);
  }

  public boolean getEnableLogging() {
    return klcppwrapJNI.MUCRoomConfig_enableLogging_get(swigCPtr, this);
  }

  public void setEnableChangeSubject(boolean value) {
    klcppwrapJNI.MUCRoomConfig_enableChangeSubject_set(swigCPtr, this, value);
  }

  public boolean getEnableChangeSubject() {
    return klcppwrapJNI.MUCRoomConfig_enableChangeSubject_get(swigCPtr, this);
  }

  public void setIsPublic(boolean value) {
    klcppwrapJNI.MUCRoomConfig_isPublic_set(swigCPtr, this, value);
  }

  public boolean getIsPublic() {
    return klcppwrapJNI.MUCRoomConfig_isPublic_get(swigCPtr, this);
  }

  public void setIsPersistent(boolean value) {
    klcppwrapJNI.MUCRoomConfig_isPersistent_set(swigCPtr, this, value);
  }

  public boolean getIsPersistent() {
    return klcppwrapJNI.MUCRoomConfig_isPersistent_get(swigCPtr, this);
  }

  public void setIsModerated(boolean value) {
    klcppwrapJNI.MUCRoomConfig_isModerated_set(swigCPtr, this, value);
  }

  public boolean getIsModerated() {
    return klcppwrapJNI.MUCRoomConfig_isModerated_get(swigCPtr, this);
  }

  public void setIsMembersOnly(boolean value) {
    klcppwrapJNI.MUCRoomConfig_isMembersOnly_set(swigCPtr, this, value);
  }

  public boolean getIsMembersOnly() {
    return klcppwrapJNI.MUCRoomConfig_isMembersOnly_get(swigCPtr, this);
  }

  public void setIsPasswordProtected(boolean value) {
    klcppwrapJNI.MUCRoomConfig_isPasswordProtected_set(swigCPtr, this, value);
  }

  public boolean getIsPasswordProtected() {
    return klcppwrapJNI.MUCRoomConfig_isPasswordProtected_get(swigCPtr, this);
  }

  public void setRoompassword(String value) {
    klcppwrapJNI.MUCRoomConfig_roompassword_set(swigCPtr, this, value);
  }

  public String getRoompassword() {
    return klcppwrapJNI.MUCRoomConfig_roompassword_get(swigCPtr, this);
  }

}
