/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class MUCRoomInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MUCRoomInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MUCRoomInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_MUCRoomInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MUCRoomInfo() {
    this(klcppwrapJNI.new_MUCRoomInfo(), true);
  }

  public void setRoomname(String value) {
    klcppwrapJNI.MUCRoomInfo_roomname_set(swigCPtr, this, value);
  }

  public String getRoomname() {
    return klcppwrapJNI.MUCRoomInfo_roomname_get(swigCPtr, this);
  }

  public void setRoomdesc(String value) {
    klcppwrapJNI.MUCRoomInfo_roomdesc_set(swigCPtr, this, value);
  }

  public String getRoomdesc() {
    return klcppwrapJNI.MUCRoomInfo_roomdesc_get(swigCPtr, this);
  }

  public void setRoomsubject(String value) {
    klcppwrapJNI.MUCRoomInfo_roomsubject_set(swigCPtr, this, value);
  }

  public String getRoomsubject() {
    return klcppwrapJNI.MUCRoomInfo_roomsubject_get(swigCPtr, this);
  }

  public void setOccupants(int value) {
    klcppwrapJNI.MUCRoomInfo_occupants_set(swigCPtr, this, value);
  }

  public int getOccupants() {
    return klcppwrapJNI.MUCRoomInfo_occupants_get(swigCPtr, this);
  }

  public void setCreationdate(String value) {
    klcppwrapJNI.MUCRoomInfo_creationdate_set(swigCPtr, this, value);
  }

  public String getCreationdate() {
    return klcppwrapJNI.MUCRoomInfo_creationdate_get(swigCPtr, this);
  }

  public void setIsPublic(boolean value) {
    klcppwrapJNI.MUCRoomInfo_isPublic_set(swigCPtr, this, value);
  }

  public boolean getIsPublic() {
    return klcppwrapJNI.MUCRoomInfo_isPublic_get(swigCPtr, this);
  }

  public void setIsPersistent(boolean value) {
    klcppwrapJNI.MUCRoomInfo_isPersistent_set(swigCPtr, this, value);
  }

  public boolean getIsPersistent() {
    return klcppwrapJNI.MUCRoomInfo_isPersistent_get(swigCPtr, this);
  }

  public void setIsModerated(boolean value) {
    klcppwrapJNI.MUCRoomInfo_isModerated_set(swigCPtr, this, value);
  }

  public boolean getIsModerated() {
    return klcppwrapJNI.MUCRoomInfo_isModerated_get(swigCPtr, this);
  }

  public void setIsMembersOnly(boolean value) {
    klcppwrapJNI.MUCRoomInfo_isMembersOnly_set(swigCPtr, this, value);
  }

  public boolean getIsMembersOnly() {
    return klcppwrapJNI.MUCRoomInfo_isMembersOnly_get(swigCPtr, this);
  }

  public void setIsPasswordProtected(boolean value) {
    klcppwrapJNI.MUCRoomInfo_isPasswordProtected_set(swigCPtr, this, value);
  }

  public boolean getIsPasswordProtected() {
    return klcppwrapJNI.MUCRoomInfo_isPasswordProtected_get(swigCPtr, this);
  }

  public void setIsNonAnonymous(boolean value) {
    klcppwrapJNI.MUCRoomInfo_isNonAnonymous_set(swigCPtr, this, value);
  }

  public boolean getIsNonAnonymous() {
    return klcppwrapJNI.MUCRoomInfo_isNonAnonymous_get(swigCPtr, this);
  }

}
