/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class RosterItem {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RosterItem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RosterItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_RosterItem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RosterItem(String jid, String name) {
    this(klcppwrapJNI.new_RosterItem__SWIG_0(jid, name), true);
  }

  public RosterItem(String jid) {
    this(klcppwrapJNI.new_RosterItem__SWIG_1(jid), true);
  }

  public String name() {
    return klcppwrapJNI.RosterItem_name(swigCPtr, this);
  }

  public String jid() {
    return klcppwrapJNI.RosterItem_jid(swigCPtr, this);
  }

  public SubscriptionType subscription() {
    return SubscriptionType.swigToEnum(klcppwrapJNI.RosterItem_subscription(swigCPtr, this));
  }

  public StringList groups() {
    return new StringList(klcppwrapJNI.RosterItem_groups(swigCPtr, this), true);
  }

  public boolean changed() {
    return klcppwrapJNI.RosterItem_changed(swigCPtr, this);
  }

  public boolean online() {
    return klcppwrapJNI.RosterItem_online(swigCPtr, this);
  }

}
