/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class Roster {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Roster(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Roster obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_Roster(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Roster() {
    this(klcppwrapJNI.new_Roster__SWIG_0(), true);
  }

  public Roster(Roster arg0) {
    this(klcppwrapJNI.new_Roster__SWIG_1(Roster.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return klcppwrapJNI.Roster_size(swigCPtr, this);
  }

  public boolean empty() {
    return klcppwrapJNI.Roster_empty(swigCPtr, this);
  }

  public void clear() {
    klcppwrapJNI.Roster_clear(swigCPtr, this);
  }

  public StringList keys() {
    return new StringList(klcppwrapJNI.Roster_keys(swigCPtr, this), true);
  }

  public RosterItem get(String key) {
    long cPtr = klcppwrapJNI.Roster_get(swigCPtr, this, key);
    return (cPtr == 0) ? null : new RosterItem(cPtr, false);
  }

  public void set(String key, RosterItem x) {
    klcppwrapJNI.Roster_set(swigCPtr, this, key, RosterItem.getCPtr(x), x);
  }

  public void del(String key) {
    klcppwrapJNI.Roster_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return klcppwrapJNI.Roster_has_key(swigCPtr, this, key);
  }

}
