/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public final class SaslMechanism {
  public final static SaslMechanism SaslMechNone = new SaslMechanism("SaslMechNone", klcppwrapJNI.SaslMechNone_get());
  public final static SaslMechanism SaslMechScramSha1 = new SaslMechanism("SaslMechScramSha1", klcppwrapJNI.SaslMechScramSha1_get());
  public final static SaslMechanism SaslMechScramSha1Plus = new SaslMechanism("SaslMechScramSha1Plus", klcppwrapJNI.SaslMechScramSha1Plus_get());
  public final static SaslMechanism SaslMechDigestMd5 = new SaslMechanism("SaslMechDigestMd5", klcppwrapJNI.SaslMechDigestMd5_get());
  public final static SaslMechanism SaslMechPlain = new SaslMechanism("SaslMechPlain", klcppwrapJNI.SaslMechPlain_get());
  public final static SaslMechanism SaslMechAnonymous = new SaslMechanism("SaslMechAnonymous", klcppwrapJNI.SaslMechAnonymous_get());
  public final static SaslMechanism SaslMechExternal = new SaslMechanism("SaslMechExternal", klcppwrapJNI.SaslMechExternal_get());
  public final static SaslMechanism SaslMechGssapi = new SaslMechanism("SaslMechGssapi", klcppwrapJNI.SaslMechGssapi_get());
  public final static SaslMechanism SaslMechNTLM = new SaslMechanism("SaslMechNTLM", klcppwrapJNI.SaslMechNTLM_get());
  public final static SaslMechanism SaslMechAll = new SaslMechanism("SaslMechAll", klcppwrapJNI.SaslMechAll_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SaslMechanism swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SaslMechanism.class + " with value " + swigValue);
  }

  private SaslMechanism(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SaslMechanism(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SaslMechanism(String swigName, SaslMechanism swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SaslMechanism[] swigValues = { SaslMechNone, SaslMechScramSha1, SaslMechScramSha1Plus, SaslMechDigestMd5, SaslMechPlain, SaslMechAnonymous, SaslMechExternal, SaslMechGssapi, SaslMechNTLM, SaslMechAll };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

