/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public final class SessionCreateError {
  public final static SessionCreateError ScErrorUnknownError = new SessionCreateError("ScErrorUnknownError");
  public final static SessionCreateError ScErrorInternalServerError = new SessionCreateError("ScErrorInternalServerError");
  public final static SessionCreateError ScErrorForbidden = new SessionCreateError("ScErrorForbidden");
  public final static SessionCreateError ScErrorConflict = new SessionCreateError("ScErrorConflict");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SessionCreateError swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SessionCreateError.class + " with value " + swigValue);
  }

  private SessionCreateError(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SessionCreateError(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SessionCreateError(String swigName, SessionCreateError swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SessionCreateError[] swigValues = { ScErrorUnknownError, ScErrorInternalServerError, ScErrorForbidden, ScErrorConflict };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

