/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class SID {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_SID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSid(String value) {
    klcppwrapJNI.SID_sid_set(swigCPtr, this, value);
  }

  public String getSid() {
    return klcppwrapJNI.SID_sid_get(swigCPtr, this);
  }

  public SID() {
    this(klcppwrapJNI.new_SID(), true);
  }

}
