/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class SIProfileFT {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SIProfileFT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SIProfileFT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_SIProfileFT(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public final static class StreamType {
    public final static SIProfileFT.StreamType FTTypeS5B = new SIProfileFT.StreamType("FTTypeS5B", klcppwrapJNI.SIProfileFT_FTTypeS5B_get());
    public final static SIProfileFT.StreamType FTTypeIBB = new SIProfileFT.StreamType("FTTypeIBB", klcppwrapJNI.SIProfileFT_FTTypeIBB_get());
    public final static SIProfileFT.StreamType FTTypeOOB = new SIProfileFT.StreamType("FTTypeOOB", klcppwrapJNI.SIProfileFT_FTTypeOOB_get());
    public final static SIProfileFT.StreamType FTTypeAll = new SIProfileFT.StreamType("FTTypeAll", klcppwrapJNI.SIProfileFT_FTTypeAll_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static StreamType swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + StreamType.class + " with value " + swigValue);
    }

    private StreamType(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private StreamType(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private StreamType(String swigName, StreamType swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static StreamType[] swigValues = { FTTypeS5B, FTTypeIBB, FTTypeOOB, FTTypeAll };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
