/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public final class StanzaErrorType {
  public final static StanzaErrorType StanzaErrorTypeAuth = new StanzaErrorType("StanzaErrorTypeAuth");
  public final static StanzaErrorType StanzaErrorTypeCancel = new StanzaErrorType("StanzaErrorTypeCancel");
  public final static StanzaErrorType StanzaErrorTypeContinue = new StanzaErrorType("StanzaErrorTypeContinue");
  public final static StanzaErrorType StanzaErrorTypeModify = new StanzaErrorType("StanzaErrorTypeModify");
  public final static StanzaErrorType StanzaErrorTypeWait = new StanzaErrorType("StanzaErrorTypeWait");
  public final static StanzaErrorType StanzaErrorTypeUndefined = new StanzaErrorType("StanzaErrorTypeUndefined");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static StanzaErrorType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + StanzaErrorType.class + " with value " + swigValue);
  }

  private StanzaErrorType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private StanzaErrorType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private StanzaErrorType(String swigName, StanzaErrorType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static StanzaErrorType[] swigValues = { StanzaErrorTypeAuth, StanzaErrorTypeCancel, StanzaErrorTypeContinue, StanzaErrorTypeModify, StanzaErrorTypeWait, StanzaErrorTypeUndefined };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

