/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public final class StanzaExtensionType {
  public final static StanzaExtensionType ExtDirectMUCInvitation = new StanzaExtensionType("ExtDirectMUCInvitation", klcppwrapJNI.ExtDirectMUCInvitation_get());
  public final static StanzaExtensionType ExtGeoloc = new StanzaExtensionType("ExtGeoloc", klcppwrapJNI.ExtGeoloc_get());
  public final static StanzaExtensionType ExtIMailSMTPInfo = new StanzaExtensionType("ExtIMailSMTPInfo", klcppwrapJNI.ExtIMailSMTPInfo_get());
  public final static StanzaExtensionType ExtMUCRoomRegistration = new StanzaExtensionType("ExtMUCRoomRegistration", klcppwrapJNI.ExtMUCRoomRegistration_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static StanzaExtensionType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + StanzaExtensionType.class + " with value " + swigValue);
  }

  private StanzaExtensionType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private StanzaExtensionType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private StanzaExtensionType(String swigName, StanzaExtensionType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static StanzaExtensionType[] swigValues = { ExtDirectMUCInvitation, ExtGeoloc, ExtIMailSMTPInfo, ExtMUCRoomRegistration };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

