/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class Stanza {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Stanza(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Stanza obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_Stanza(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public JID from() {
    return new JID(klcppwrapJNI.Stanza_from(swigCPtr, this), false);
  }

  public JID to() {
    return new JID(klcppwrapJNI.Stanza_to(swigCPtr, this), false);
  }

  public String id() {
    return klcppwrapJNI.Stanza_id(swigCPtr, this);
  }

  public String xmlLang() {
    return klcppwrapJNI.Stanza_xmlLang(swigCPtr, this);
  }

}
