/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public final class StanzaError {
  public final static StanzaError StanzaErrorBadRequest = new StanzaError("StanzaErrorBadRequest");
  public final static StanzaError StanzaErrorConflict = new StanzaError("StanzaErrorConflict");
  public final static StanzaError StanzaErrorFeatureNotImplemented = new StanzaError("StanzaErrorFeatureNotImplemented");
  public final static StanzaError StanzaErrorForbidden = new StanzaError("StanzaErrorForbidden");
  public final static StanzaError StanzaErrorGone = new StanzaError("StanzaErrorGone");
  public final static StanzaError StanzaErrorInternalServerError = new StanzaError("StanzaErrorInternalServerError");
  public final static StanzaError StanzaErrorItemNotFound = new StanzaError("StanzaErrorItemNotFound");
  public final static StanzaError StanzaErrorJidMalformed = new StanzaError("StanzaErrorJidMalformed");
  public final static StanzaError StanzaErrorNotAcceptable = new StanzaError("StanzaErrorNotAcceptable");
  public final static StanzaError StanzaErrorNotAllowed = new StanzaError("StanzaErrorNotAllowed");
  public final static StanzaError StanzaErrorNotAuthorized = new StanzaError("StanzaErrorNotAuthorized");
  public final static StanzaError StanzaErrorNotModified = new StanzaError("StanzaErrorNotModified");
  public final static StanzaError StanzaErrorPaymentRequired = new StanzaError("StanzaErrorPaymentRequired");
  public final static StanzaError StanzaErrorRecipientUnavailable = new StanzaError("StanzaErrorRecipientUnavailable");
  public final static StanzaError StanzaErrorRedirect = new StanzaError("StanzaErrorRedirect");
  public final static StanzaError StanzaErrorRegistrationRequired = new StanzaError("StanzaErrorRegistrationRequired");
  public final static StanzaError StanzaErrorRemoteServerNotFound = new StanzaError("StanzaErrorRemoteServerNotFound");
  public final static StanzaError StanzaErrorRemoteServerTimeout = new StanzaError("StanzaErrorRemoteServerTimeout");
  public final static StanzaError StanzaErrorResourceConstraint = new StanzaError("StanzaErrorResourceConstraint");
  public final static StanzaError StanzaErrorServiceUnavailable = new StanzaError("StanzaErrorServiceUnavailable");
  public final static StanzaError StanzaErrorSubscribtionRequired = new StanzaError("StanzaErrorSubscribtionRequired");
  public final static StanzaError StanzaErrorUndefinedCondition = new StanzaError("StanzaErrorUndefinedCondition");
  public final static StanzaError StanzaErrorUnexpectedRequest = new StanzaError("StanzaErrorUnexpectedRequest");
  public final static StanzaError StanzaErrorUnknownSender = new StanzaError("StanzaErrorUnknownSender");
  public final static StanzaError StanzaErrorUndefined = new StanzaError("StanzaErrorUndefined");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static StanzaError swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + StanzaError.class + " with value " + swigValue);
  }

  private StanzaError(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private StanzaError(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private StanzaError(String swigName, StanzaError swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static StanzaError[] swigValues = { StanzaErrorBadRequest, StanzaErrorConflict, StanzaErrorFeatureNotImplemented, StanzaErrorForbidden, StanzaErrorGone, StanzaErrorInternalServerError, StanzaErrorItemNotFound, StanzaErrorJidMalformed, StanzaErrorNotAcceptable, StanzaErrorNotAllowed, StanzaErrorNotAuthorized, StanzaErrorNotModified, StanzaErrorPaymentRequired, StanzaErrorRecipientUnavailable, StanzaErrorRedirect, StanzaErrorRegistrationRequired, StanzaErrorRemoteServerNotFound, StanzaErrorRemoteServerTimeout, StanzaErrorResourceConstraint, StanzaErrorServiceUnavailable, StanzaErrorSubscribtionRequired, StanzaErrorUndefinedCondition, StanzaErrorUnexpectedRequest, StanzaErrorUnknownSender, StanzaErrorUndefined };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

