/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public final class StreamFeature {
  public final static StreamFeature StreamFeatureBind = new StreamFeature("StreamFeatureBind", klcppwrapJNI.StreamFeatureBind_get());
  public final static StreamFeature StreamFeatureUnbind = new StreamFeature("StreamFeatureUnbind", klcppwrapJNI.StreamFeatureUnbind_get());
  public final static StreamFeature StreamFeatureSession = new StreamFeature("StreamFeatureSession", klcppwrapJNI.StreamFeatureSession_get());
  public final static StreamFeature StreamFeatureStartTls = new StreamFeature("StreamFeatureStartTls", klcppwrapJNI.StreamFeatureStartTls_get());
  public final static StreamFeature StreamFeatureIqRegister = new StreamFeature("StreamFeatureIqRegister", klcppwrapJNI.StreamFeatureIqRegister_get());
  public final static StreamFeature StreamFeatureIqAuth = new StreamFeature("StreamFeatureIqAuth", klcppwrapJNI.StreamFeatureIqAuth_get());
  public final static StreamFeature StreamFeatureCompressZlib = new StreamFeature("StreamFeatureCompressZlib", klcppwrapJNI.StreamFeatureCompressZlib_get());
  public final static StreamFeature StreamFeatureCompressDclz = new StreamFeature("StreamFeatureCompressDclz", klcppwrapJNI.StreamFeatureCompressDclz_get());
  public final static StreamFeature StreamFeatureStreamManagement = new StreamFeature("StreamFeatureStreamManagement", klcppwrapJNI.StreamFeatureStreamManagement_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static StreamFeature swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + StreamFeature.class + " with value " + swigValue);
  }

  private StreamFeature(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private StreamFeature(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private StreamFeature(String swigName, StreamFeature swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static StreamFeature[] swigValues = { StreamFeatureBind, StreamFeatureUnbind, StreamFeatureSession, StreamFeatureStartTls, StreamFeatureIqRegister, StreamFeatureIqAuth, StreamFeatureCompressZlib, StreamFeatureCompressDclz, StreamFeatureStreamManagement };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

