/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public final class SubscriptionType {
  public final static SubscriptionType S10nNone = new SubscriptionType("S10nNone");
  public final static SubscriptionType S10nNoneOut = new SubscriptionType("S10nNoneOut");
  public final static SubscriptionType S10nNoneIn = new SubscriptionType("S10nNoneIn");
  public final static SubscriptionType S10nNoneOutIn = new SubscriptionType("S10nNoneOutIn");
  public final static SubscriptionType S10nTo = new SubscriptionType("S10nTo");
  public final static SubscriptionType S10nToIn = new SubscriptionType("S10nToIn");
  public final static SubscriptionType S10nFrom = new SubscriptionType("S10nFrom");
  public final static SubscriptionType S10nFromOut = new SubscriptionType("S10nFromOut");
  public final static SubscriptionType S10nBoth = new SubscriptionType("S10nBoth");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SubscriptionType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SubscriptionType.class + " with value " + swigValue);
  }

  private SubscriptionType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SubscriptionType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SubscriptionType(String swigName, SubscriptionType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SubscriptionType[] swigValues = { S10nNone, S10nNoneOut, S10nNoneIn, S10nNoneOutIn, S10nTo, S10nToIn, S10nFrom, S10nFromOut, S10nBoth };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

