/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public final class TLSPolicy {
  public final static TLSPolicy TLSDisabled = new TLSPolicy("TLSDisabled");
  public final static TLSPolicy TLSOptional = new TLSPolicy("TLSOptional");
  public final static TLSPolicy TLSRequired = new TLSPolicy("TLSRequired");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TLSPolicy swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TLSPolicy.class + " with value " + swigValue);
  }

  private TLSPolicy(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TLSPolicy(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TLSPolicy(String swigName, TLSPolicy swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TLSPolicy[] swigValues = { TLSDisabled, TLSOptional, TLSRequired };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

