/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class VCardName {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VCardName(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VCardName obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_VCardName(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VCardName() {
    this(klcppwrapJNI.new_VCardName(), true);
  }

  public String family() {
    return klcppwrapJNI.VCardName_family(swigCPtr, this);
  }

  public String given() {
    return klcppwrapJNI.VCardName_given(swigCPtr, this);
  }

  public String middle() {
    return klcppwrapJNI.VCardName_middle(swigCPtr, this);
  }

  public String prefix() {
    return klcppwrapJNI.VCardName_prefix(swigCPtr, this);
  }

  public String suffix() {
    return klcppwrapJNI.VCardName_suffix(swigCPtr, this);
  }

  public void setFamily(String family_) {
    klcppwrapJNI.VCardName_setFamily(swigCPtr, this, family_);
  }

  public void setGiven(String given_) {
    klcppwrapJNI.VCardName_setGiven(swigCPtr, this, given_);
  }

  public void setMiddle(String middle_) {
    klcppwrapJNI.VCardName_setMiddle(swigCPtr, this, middle_);
  }

  public void setPrefix(String prefix_) {
    klcppwrapJNI.VCardName_setPrefix(swigCPtr, this, prefix_);
  }

  public void setSuffix(String suffix_) {
    klcppwrapJNI.VCardName_setSuffix(swigCPtr, this, suffix_);
  }

}
