/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class VCardTelephone {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VCardTelephone(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VCardTelephone obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_VCardTelephone(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VCardTelephone() {
    this(klcppwrapJNI.new_VCardTelephone(), true);
  }

  public void setNumber(String number_) {
    klcppwrapJNI.VCardTelephone_setNumber(swigCPtr, this, number_);
  }

  public String number() {
    return klcppwrapJNI.VCardTelephone_number(swigCPtr, this);
  }

  public boolean isHome() {
    return klcppwrapJNI.VCardTelephone_isHome(swigCPtr, this);
  }

  public boolean isWork() {
    return klcppwrapJNI.VCardTelephone_isWork(swigCPtr, this);
  }

  public boolean isVoice() {
    return klcppwrapJNI.VCardTelephone_isVoice(swigCPtr, this);
  }

  public boolean isFax() {
    return klcppwrapJNI.VCardTelephone_isFax(swigCPtr, this);
  }

  public boolean isPager() {
    return klcppwrapJNI.VCardTelephone_isPager(swigCPtr, this);
  }

  public boolean isMsg() {
    return klcppwrapJNI.VCardTelephone_isMsg(swigCPtr, this);
  }

  public boolean isCell() {
    return klcppwrapJNI.VCardTelephone_isCell(swigCPtr, this);
  }

  public boolean isVideo() {
    return klcppwrapJNI.VCardTelephone_isVideo(swigCPtr, this);
  }

  public boolean isBBS() {
    return klcppwrapJNI.VCardTelephone_isBBS(swigCPtr, this);
  }

  public boolean isModem() {
    return klcppwrapJNI.VCardTelephone_isModem(swigCPtr, this);
  }

  public boolean isISDN() {
    return klcppwrapJNI.VCardTelephone_isISDN(swigCPtr, this);
  }

  public boolean isPCS() {
    return klcppwrapJNI.VCardTelephone_isPCS(swigCPtr, this);
  }

  public boolean isPref() {
    return klcppwrapJNI.VCardTelephone_isPref(swigCPtr, this);
  }

  public void setType(int type_) {
    klcppwrapJNI.VCardTelephone_setType(swigCPtr, this, type_);
  }

}
