/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class VCardLabel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VCardLabel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VCardLabel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_VCardLabel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VCardLabel() {
    this(klcppwrapJNI.new_VCardLabel(), true);
  }

  public void setLines(StringList lines_) {
    klcppwrapJNI.VCardLabel_setLines(swigCPtr, this, StringList.getCPtr(lines_), lines_);
  }

  public StringList lines() {
    return new StringList(klcppwrapJNI.VCardLabel_lines(swigCPtr, this), false);
  }

  public boolean isHome() {
    return klcppwrapJNI.VCardLabel_isHome(swigCPtr, this);
  }

  public boolean isWork() {
    return klcppwrapJNI.VCardLabel_isWork(swigCPtr, this);
  }

  public boolean isPostal() {
    return klcppwrapJNI.VCardLabel_isPostal(swigCPtr, this);
  }

  public boolean isParcel() {
    return klcppwrapJNI.VCardLabel_isParcel(swigCPtr, this);
  }

  public boolean isPref() {
    return klcppwrapJNI.VCardLabel_isPref(swigCPtr, this);
  }

  public boolean isDom() {
    return klcppwrapJNI.VCardLabel_isDom(swigCPtr, this);
  }

  public boolean isIntl() {
    return klcppwrapJNI.VCardLabel_isIntl(swigCPtr, this);
  }

  public void setType(int type_) {
    klcppwrapJNI.VCardLabel_setType(swigCPtr, this, type_);
  }

}
