/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class VCardOrg {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VCardOrg(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VCardOrg obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_VCardOrg(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VCardOrg() {
    this(klcppwrapJNI.new_VCardOrg(), true);
  }

  public void setName(String name_) {
    klcppwrapJNI.VCardOrg_setName(swigCPtr, this, name_);
  }

  public String name() {
    return klcppwrapJNI.VCardOrg_name(swigCPtr, this);
  }

  public void setUnits(StringList units_) {
    klcppwrapJNI.VCardOrg_setUnits(swigCPtr, this, StringList.getCPtr(units_), units_);
  }

  public StringList units() {
    return new StringList(klcppwrapJNI.VCardOrg_units(swigCPtr, this), false);
  }

}
