/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class VCardLabelList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VCardLabelList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VCardLabelList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_VCardLabelList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VCardLabelList() {
    this(klcppwrapJNI.new_VCardLabelList(), true);
  }

  public long size() {
    return klcppwrapJNI.VCardLabelList_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return klcppwrapJNI.VCardLabelList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    klcppwrapJNI.VCardLabelList_clear(swigCPtr, this);
  }

  public void add(VCardLabel x) {
    klcppwrapJNI.VCardLabelList_add(swigCPtr, this, VCardLabel.getCPtr(x), x);
  }

  public VCardLabel get(int index) {
    long cPtr = klcppwrapJNI.VCardLabelList_get(swigCPtr, this, index);
    return (cPtr == 0) ? null : new VCardLabel(cPtr, false);
  }

}
