/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class VCardAddress {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VCardAddress(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VCardAddress obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_VCardAddress(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VCardAddress() {
    this(klcppwrapJNI.new_VCardAddress(), true);
  }

  public void setPobox(String pobox_) {
    klcppwrapJNI.VCardAddress_setPobox(swigCPtr, this, pobox_);
  }

  public String pobox() {
    return klcppwrapJNI.VCardAddress_pobox(swigCPtr, this);
  }

  public void setExtadd(String extadd_) {
    klcppwrapJNI.VCardAddress_setExtadd(swigCPtr, this, extadd_);
  }

  public String extadd() {
    return klcppwrapJNI.VCardAddress_extadd(swigCPtr, this);
  }

  public void setStreet(String street_) {
    klcppwrapJNI.VCardAddress_setStreet(swigCPtr, this, street_);
  }

  public String street() {
    return klcppwrapJNI.VCardAddress_street(swigCPtr, this);
  }

  public void setLocality(String locality_) {
    klcppwrapJNI.VCardAddress_setLocality(swigCPtr, this, locality_);
  }

  public String locality() {
    return klcppwrapJNI.VCardAddress_locality(swigCPtr, this);
  }

  public void setRegion(String region_) {
    klcppwrapJNI.VCardAddress_setRegion(swigCPtr, this, region_);
  }

  public String region() {
    return klcppwrapJNI.VCardAddress_region(swigCPtr, this);
  }

  public void setPcode(String pcode_) {
    klcppwrapJNI.VCardAddress_setPcode(swigCPtr, this, pcode_);
  }

  public String pcode() {
    return klcppwrapJNI.VCardAddress_pcode(swigCPtr, this);
  }

  public void setCtry(String ctry_) {
    klcppwrapJNI.VCardAddress_setCtry(swigCPtr, this, ctry_);
  }

  public String ctry() {
    return klcppwrapJNI.VCardAddress_ctry(swigCPtr, this);
  }

  public boolean isHome() {
    return klcppwrapJNI.VCardAddress_isHome(swigCPtr, this);
  }

  public boolean isWork() {
    return klcppwrapJNI.VCardAddress_isWork(swigCPtr, this);
  }

  public boolean isPostal() {
    return klcppwrapJNI.VCardAddress_isPostal(swigCPtr, this);
  }

  public boolean isParcel() {
    return klcppwrapJNI.VCardAddress_isParcel(swigCPtr, this);
  }

  public boolean isPref() {
    return klcppwrapJNI.VCardAddress_isPref(swigCPtr, this);
  }

  public boolean isDom() {
    return klcppwrapJNI.VCardAddress_isDom(swigCPtr, this);
  }

  public boolean isIntl() {
    return klcppwrapJNI.VCardAddress_isIntl(swigCPtr, this);
  }

  public void setType(int type_) {
    klcppwrapJNI.VCardAddress_setType(swigCPtr, this, type_);
  }

}
