/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class VCardEmail {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VCardEmail(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VCardEmail obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_VCardEmail(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VCardEmail() {
    this(klcppwrapJNI.new_VCardEmail(), true);
  }

  public void setUserid(String userid_) {
    klcppwrapJNI.VCardEmail_setUserid(swigCPtr, this, userid_);
  }

  public String userid() {
    return klcppwrapJNI.VCardEmail_userid(swigCPtr, this);
  }

  public boolean isHome() {
    return klcppwrapJNI.VCardEmail_isHome(swigCPtr, this);
  }

  public boolean isWork() {
    return klcppwrapJNI.VCardEmail_isWork(swigCPtr, this);
  }

  public boolean isInternet() {
    return klcppwrapJNI.VCardEmail_isInternet(swigCPtr, this);
  }

  public boolean isPref() {
    return klcppwrapJNI.VCardEmail_isPref(swigCPtr, this);
  }

  public boolean isX400() {
    return klcppwrapJNI.VCardEmail_isX400(swigCPtr, this);
  }

  public void setType(int type_) {
    klcppwrapJNI.VCardEmail_setType(swigCPtr, this, type_);
  }

}
