/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class VCardTelephponeList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VCardTelephponeList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VCardTelephponeList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_VCardTelephponeList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VCardTelephponeList() {
    this(klcppwrapJNI.new_VCardTelephponeList(), true);
  }

  public long size() {
    return klcppwrapJNI.VCardTelephponeList_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return klcppwrapJNI.VCardTelephponeList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    klcppwrapJNI.VCardTelephponeList_clear(swigCPtr, this);
  }

  public void add(VCardTelephone x) {
    klcppwrapJNI.VCardTelephponeList_add(swigCPtr, this, VCardTelephone.getCPtr(x), x);
  }

  public VCardTelephone get(int index) {
    long cPtr = klcppwrapJNI.VCardTelephponeList_get(swigCPtr, this, index);
    return (cPtr == 0) ? null : new VCardTelephone(cPtr, false);
  }

}
