/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class VCardPhoto {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VCardPhoto(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VCardPhoto obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_VCardPhoto(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VCardPhoto() {
    this(klcppwrapJNI.new_VCardPhoto(), true);
  }

  public void setExtval(String extval_) {
    klcppwrapJNI.VCardPhoto_setExtval(swigCPtr, this, extval_);
  }

  public String extval() {
    return klcppwrapJNI.VCardPhoto_extval(swigCPtr, this);
  }

  public void setBinval(String binval_) {
    klcppwrapJNI.VCardPhoto_setBinval(swigCPtr, this, binval_);
  }

  public String binval() {
    return klcppwrapJNI.VCardPhoto_binval(swigCPtr, this);
  }

  public void setType(String type_) {
    klcppwrapJNI.VCardPhoto_setType(swigCPtr, this, type_);
  }

  public String type() {
    return klcppwrapJNI.VCardPhoto_type(swigCPtr, this);
  }

}
