/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xmpp.myWRAP;

public class VCardGeo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VCardGeo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VCardGeo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        klcppwrapJNI.delete_VCardGeo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VCardGeo() {
    this(klcppwrapJNI.new_VCardGeo(), true);
  }

  public void setLatitude(String latitude_) {
    klcppwrapJNI.VCardGeo_setLatitude(swigCPtr, this, latitude_);
  }

  public String latitude() {
    return klcppwrapJNI.VCardGeo_latitude(swigCPtr, this);
  }

  public void setLongitude(String longitude_) {
    klcppwrapJNI.VCardGeo_setLongitude(swigCPtr, this, longitude_);
  }

  public String longitude() {
    return klcppwrapJNI.VCardGeo_longitude(swigCPtr, this);
  }

}
